# Dockerfile.mlflow
FROM python:3.11.4-slim

RUN apt-get update && apt-get install -y curl && \
    pip install uv && \
    uv pip install --no-cache-dir mlflow==2.22.0 --system

EXPOSE 8080

CMD mlflow server \
    --host 0.0.0.0 \
    --port 8080 \
    --backend-store-uri sqlite:///mlflow-db/mlflow.db \
    --default-artifact-root /mlflow-artifacts